site_name: Ethos Project Documentation
theme:
  name: material
  logo: assets/ethos.svg
  features:
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight
  palette:
    primary: red
nav:
  - Overview: index.md
  - 'Ethos Base Station': 'https://github.com/climate-ethos/ethos-raspberry-pi/blob/master/README.md'
  - 'Ethos Temperature Sensor': 'https://github.com/climate-ethos/ethos-raspberry-pi/blob/master/README.md'
  - 'Ethos Server': 'https://github.com/climate-ethos/ethos-server/blob/master/README.md'
  - 'Publications & News Articles': publications.md
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format