site_name: Ethos Project Documentation

theme:
  name: material
  logo: assets/ethos.svg
  features:
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight
  palette:
    primary: red

plugins:
  - search
  - multirepo:
      cleanup: true
      nav_repos:
        - name: ethos-base-station
          import_url: https://github.com/climate-ethos/ethos-base-station
          imports: [/README.md, /assets]
        - name: ethos-temperature-sensor
          import_url: https://github.com/climate-ethos/ethos-temperature-sensor?branch=main
          imports: [/README.md]
        - name: ethos-server
          import_url: https://github.com/climate-ethos/ethos-server?branch=main
          imports: [/README.md]

nav:
  - Overview: index.md
  - 'Ethos Base Station': 'ethos-base-station/README.md'
  - 'Ethos Temperature Sensor': 'ethos-temperature-sensor/README.md'
  - 'Ethos Server': 'ethos-server/README.md'
  - 'Publications & News Articles': publications.md

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format